### ISSUE TITLE
No icon for accounts/rooms without a set image

### ISSUE THREAD

**Issue by imbev** [commetchat/commet#111]
**Describe the bug**
There is no icon fallback for accounts/rooms that don't have a set image.

**To Reproduce**
1. Don't set an image for an account or room

**Expected behavior**
A fallback icon with letters based on the account/room name

<details open>
<summary>Device Information</summary>
<br>

**Device**
Platform: `web`
Version: `v0.1.0`
Git Hash: `f2b3ca0b0a7d6fc7dc0ec6cf073d7c2c7c464dd3`
Detail: `default`

**System Info**

Product: `Gecko`
</details>

**Comment by Airyzz** [comment]
Is this referring to the left most side panel with spaces / settings button?

**Comment by Airyzz** [comment]
Closing this as im assuming this was talking about the left panel. feel free to open again if I misunderstood!
