### ISSUE TITLE
[Feature Request] AMOLED Black Theme

### ISSUE THREAD

**Issue by TheSunCat** [commetchat/commet#157]
Hi! Excited to see a new Matrix client. I downloaded it and it feels super smooth.

Before switching to it, I would love to see a AMOLED/"true black" theme as the grey doesn't pop much on my phone screen (Pixel 3a) and ends up with poor contrast. Are there plans to support this?
Thanks!

**Comment by Airyzz** [comment]
Hey, I'm all on board for an amoled theme, sounds like a great addition! 
I would also like to have support for custom themes. We can put this on the roadmap for 0.2 I reckon :)
