### ISSUE TITLE
How to translate Commet ?

### ISSUE THREAD

**Issue by Zozosticot** [commetchat/commet#158]
Hello, I'd like to translate this application into French, but I don't know how to help you. Do you plan to integrate a tool like weblate? Thank you very much!

**Comment by Airyzz** [comment]
Thanks for your interest in translating! At the moment, we don't have a tool like weblate set up. I will look in to it if there is interest, but for now it can be translated just by creating an arb file like the one [here](https://github.com/commetchat/commet/blob/main/commet/assets/l10n/intl_en.arb)

**Comment by Airyzz** [comment]
Actually, I am going to apply for Weblate Libre hosting now, I'll update with a trial repo shortly, and hopefully we can get hosted :)

**Comment by Airyzz** [comment]
We have a trial instance [here](https://hosted.weblate.org/projects/commetchat/commet/), it would be sweet if you could give it a try and let me know how it goes
