### ISSUE TITLE
Poor Performance when large amount of users loaded

### ISSUE THREAD

**Issue by Airyzz** [commetchat/commet#248]
**Describe the bug**
At the moment, commet is lazily loading the room member list, and as a result there is not typically a large amount of users loaded - In the event that we end up with loading the entire member list, performance takes a significant hit

![image](https://github.com/commetchat/commet/assets/36567925/400f7ba3-55d3-4b51-9142-d6ed052c2e1c)

**Comment by Airyzz** [comment]
This should get resolved in #249 because that call to onRoomStateUpdated no longer exists, and is not needed

**Comment by Aranjedeath** [comment]
can confirm, #249 resolves the performance issue
