### ISSUE TITLE
Thread support (MSC 3440)

### ISSUE THREAD

**Issue by notramo** [commetchat/commet#251]
Message threads (MSC 3440 - now merged into the Matrix spec) are a much requested feature for all Matrix clients, however as of now, only a few clients support it. It's the most upvoted feature for [Cinny](https://github.com/cinnyapp/cinny/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) and [FluffyChat](https://github.com/krille-chan/fluffychat/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). Thread support in Commet would help this client gain **huge** amount of popularity and new contributors.

I would be happy to donate for specifically this issue using [Polar](https://polar.sh) (Polar lets supporters decide which issue they want the money to be used for). I can't give a big amount, but it can add a little bit of motivation. Also, I'm sure others would also support this feature financially, possibly to an amount of fully backing the cost of the implementation.

**Comment by Airyzz** [comment]
Good idea, I hacked something together over in #252

**Comment by notramo** [comment]
Wow, that was fast.
