### ISSUE TITLE
Custom emojis

### ISSUE THREAD

**Issue by RatCornu** [commetchat/commet#261]
**Describe the bug**
I found several bugs related to custom emojis/stickers:
- it's only possible to add one emoji/sticker pack, after the "+" button disappears
- I could not save after trying to import a signal sticker pack: the sticker would load but not import
- when trying to send a sticker, it is shown as a file while emojis of the same image are not a problem.

**To Reproduce**
1. Go to Settings -> Stickers/Emojis -> No "+" button for new sticker pack

2. Go to Settings -> Stickers/Emojis -> Import pack -> enter any sgnl:// URL -> Cannot confirm

3. Go to any chat -> send a sticker -> Sticker not rendered as an image

**Expected behavior**

**Screenshots**
![image](https://github.com/commetchat/commet/assets/98173832/1dbb2f4b-59a9-432b-9158-8a1f309e68d6)

On this image, the emoji and the sticker are the same image, but the sticker is sent as a regular file.

**Additional context**

Here are my device information but the problem is the same on android.

<details open>
<summary>Device Information</summary>
<br>

**Device**
Platform: `windows`
Version: `v0.2.1`
Git Hash: `cf1a61c2679392dae0a72e91a1c470a472934989`
Detail: `default`

**System Info**

</details>

**Comment by Airyzz** [comment]
> it's only possible to add one emoji/sticker pack, after the "+" button disappears

This is intended behavior, you can only have one custom pack stored in your profile. For extra packs, you need to add them to a room and mark as global

> I could not save after trying to import a signal sticker pack: the sticker would load but not import

Can you provide more information about the pack you are trying to load, I can't reproduce this behavior

> when trying to send a sticker, it is shown as a file while emojis of the same image are not a problem.

Sounds like commet was unable to determine the mimetype of the image, can you provide a link to the file with this behavior

**Comment by RatCornu** [comment]
Oh okay thanks for the information, I didn't know this and I didn't find documentation online on this.
Moreover can I just ask why? I think it would be a good idea to be able to have multiple custom packs but maybe I miss something.

It's the case for every pack I tried but here is an example : 
https://signal.art/addstickers/#pack_id=fd7e2fec616c56b8aeb15c7068622175&pack_key=3cc955e37fefabebb52b2a9d581da72bee6dfbc41809f14538e1779d7120be4a (the issue is the same with the sgnl:// URL).
Steps : Import pack -> Enter URL -> Import (with or without change) -> the window is closed but nothing happened

It works indeed for some files but I have trouble with this one : 
![main](https://github.com/commetchat/commet/assets/98173832/fda3f953-4c2c-40c6-a713-1fe68e14a8b9).

Thanks for the quick reply!

**Comment by Airyzz** [comment]
> Oh okay thanks for the information, I didn't know this and I didn't find documentation online on this.
Moreover can I just ask why? I think it would be a good idea to be able to have multiple custom packs but maybe I miss something.

I agree, it would be nice. I think likely its just a way to prevent the users profile state from becoming too big and filled with tons of emoji. But since this is not actually a part of the spec, I'm just following other clients' implementations

Generally I just have a room dedicated to sticker packs that I store everything in, and just use those globally. Works well and has the bonus that you can easily share it with others if you want.


I do seem to be able to reproduce the behavior with this info, so I can look in to it soon!

**Comment by RatCornu** [comment]
Thanks! I understand that you need to make choices, and I fully support this project (I found it yesterday and I'm already in love with it ^^)! Keep doing great work!

**Comment by RatCornu** [comment]
No, I think a general documentation for your app (more like a user guide): it's a little annoying to do but I think it's worth it in the end

**Comment by Airyzz** [comment]
I think its a good idea, but it's not a priority for me
