### ISSUE TITLE
FR: room / encrypted room search

### ISSUE THREAD

**Issue by theotheroracle** [commetchat/commet#263]
there's currently no client that supports encrypted room search on mobile, so this would really set your client apart tbh, but it's also just a really useful feature that i find myself often missing

**Comment by Airyzz** [comment]
I'd love to have it, but its a pretty significant task with so many different ways to approach it. 

Do we know if there is any recommendation or reference for ways to approach it? I have some ideas but would love to see what others are doing

**Comment by Airyzz** [comment]
Adding for reference: 

https://github.com/matrix-org/seshat

https://gist.github.com/BURG3R5/fe84e6880726e5d50d09f6dab84efc9d

**Comment by theotheroracle** [comment]
i would look into nheko's implementation, it's quite fast compared to element which uses seshat in my experience

**Comment by ollietheotter983** [comment]
+1
