### ISSUE TITLE
[Bug] Names and avatars not working in bridged chats

### ISSUE THREAD

**Issue by ollietheotter983** [commetchat/commet#278]
**Describe the bug**
I cant see the proper usernames and avatars for a person in a bridged chat (im using the beeper.com homeserver that sorts bridging for you) when I can see that just fine in Ele and FC etc

**To Reproduce**
1. Open a bridged chat
2. Look at the other user avatar and name
3. Wonder where everything went wrong

**Expected behavior**
Avatars and names work properly

**Screenshots**
![Screenshot_20240622_173752](https://github.com/commetchat/commet/assets/169618018/bfa03ced-4cee-45a5-976a-3c2ef535e54f)
![Screenshot_20240622_172652](https://github.com/commetchat/commet/assets/169618018/50f36355-7797-409a-8f42-cda6e4297a65)

**Additional context**
I must hammer it in that this isnt a homeserver/bridge issue as it works in any other client

<details open>
<summary>Device Information</summary>
<br>

**Device**
Platform: `android`
Version: `v0.2.1`
Git Hash: `cf1a61c2679392dae0a72e91a1c470a472934989`
Detail: `default`

**System Info**

Product: `a34xdxx`
</details>

**Comment by ollietheotter983** [comment]
Update: can confirm, same issue on web version on Firefox android, same phone

**Comment by Airyzz** [comment]
I've just realized its possible this is actually already fixed by #249, which just isn't in any releases yet. Would explain why I'm not noticing similar issues while testing latest dev version

**Comment by ollietheotter983** [comment]
Do you have a test build perchance? Some apps on GitHub do that but idk about this bc its cross platform. I can test on Android, web and maybe Windows or Ubuntu

**Comment by Airyzz** [comment]
we do not have development builds available at the moment, its something i'm considering. If you want to test you will need to build from source unfortunately

**Comment by ollietheotter983** [comment]
Ah thats fine, I can wait until the update then

**Comment by ollietheotter983** [comment]
Fixed in the v0.3.0 dev build

**Comment by Airyzz** [comment]
awesome, thanks for testing!

**Comment by ollietheotter983** [comment]
no problem mate
