### ISSUE TITLE
Preview builds

### ISSUE THREAD

**Issue by notramo** [commetchat/commet#282]
Is it possible to test the latest dev build somehow without building it from source? If there are no CI releases, could you publish a preview release after every 3-5 pull requests? It would be helpful for catching the bugs in the new features, and being able to report them before the new release, so it's already released bug-free. Currently, when bugs are noticed in a new release, users have to wait an entire release cycle before it's fixed, due to the lack of testing with preview builds.

I think the project could benefit from faster release cycles. Why jam 2-3 new features into a release when each feature could have its own version? It would result in more TWIM appearances, and gaining popularity faster. For example, I'm sure that many users would like to try out the message threading feature.

**Comment by ollietheotter983** [comment]
+1

**Comment by Airyzz** [comment]
I agree. having more eyes on in development versions will help to bolster confidence in the stability of new features, meaning we can get to stable releases faster. I take a look and see if anything further needs to be changed in release actions and can start publishing pre-releases intermittently
