### ISSUE TITLE
SSO only server does not seem to work

### ISSUE THREAD

**Issue by Theaninova** [commetchat/commet#291]
**Describe the bug**

I have a server with an Authentik SSO and no password auth, and it won't register as a server. There were no errors in the console, no network errors, it even finds the correct server and queries it, but marks it with an ❌ and no SSO button shows up. Absolutely no indication to what went wrong.

I can log into other servers which have password auth only.

SSO of my server works in FluffyChat (which presumably uses the exact same matrix dart library?), Element and Cinny without issues, on the same network and device.

`versions`
```json
{"versions":["r0.0.1","r0.1.0","r0.2.0","r0.3.0","r0.4.0","r0.5.0","r0.6.0","r0.6.1","v1.1","v1.2","v1.3","v1.4","v1.5","v1.6","v1.7","v1.8","v1.9","v1.10"],"unstable_features":{"org.matrix.label_based_filtering":true,"org.matrix.e2e_cross_signing":true,"org.matrix.msc2432":true,"uk.half-shot.msc2666.query_mutual_rooms":true,"io.element.e2ee_forced.public":false,"io.element.e2ee_forced.private":false,"io.element.e2ee_forced.trusted_private":false,"org.matrix.msc3026.busy_presence":false,"org.matrix.msc2285.stable":true,"org.matrix.msc3827.stable":true,"org.matrix.msc3440.stable":true,"org.matrix.msc3771":true,"org.matrix.msc3773":false,"fi.mau.msc2815":false,"fi.mau.msc2659.stable":true,"org.matrix.msc3882":false,"org.matrix.msc3881":false,"org.matrix.msc3874":false,"org.matrix.msc3886":false,"org.matrix.msc3912":false,"org.matrix.msc3981":true,"org.matrix.msc3391":false,"org.matrix.msc4069":false,"org.matrix.msc4028":false,"org.matrix.msc4108":false}}
```
`login`
```json
{"flows":[{"type":"m.login.sso","identity_providers":[{"id":"oidc-authentik","name":"authentik"}]},{"type":"m.login.token"},{"type":"m.login.application_service"}]}
```

**To Reproduce**
1. Use a homeserver with SSO only (?)
2. Try to login

**Additional context**

Commet v0.2.1 cf1a61c

**Comment by Airyzz** [comment]
Interesting! would it be possible for you to share the url of your server so i can take a look, or do you know of any public servers with the same config? If you dont want to post the url in public here, happy for you to send me the url privately

**Comment by Theaninova** [comment]
Server URL is `theaninova.de`
