### ISSUE TITLE
[FEATURE] wallpaper

### ISSUE THREAD

**Issue by theotheroracle** [commetchat/commet#293]
i was requested to add wallpaper support, as in, ability to set a background for chats, i'll look into doing this :)

**Comment by Airyzz** [comment]
This is already somewhat supported by the custom theming system - we can set an image wallpaper for the app theme, however we cant specify a custom wallpaper on a per-chat basis

the theming system needs documentation, which I haven't got around to yet

**Comment by theotheroracle** [comment]
oh excellent

**Comment by Airyzz** [comment]
Documentation is now available here: https://github.com/commetchat/commet/wiki/Custom-Themes
