### ISSUE TITLE
Material you not properly working on OneUI

### ISSUE THREAD

**Issue by ollietheotter983** [commetchat/commet#318]
**Describe the bug**
Same as title

**To Reproduce**
1. Go to settings
2. Enable system colour scheme
3. Pain

**Expected behavior**
Colours should match with system colours

**Screenshots**
![Screenshot_20240718_093312](https://github.com/user-attachments/assets/db62ec8a-631c-4042-bd64-26ad4670ccae)
![Screenshot_20240719_104248_Samsung Internet](https://github.com/user-attachments/assets/d2d0ba0f-ecf9-457a-84d7-091a1849345b)
(second one to show colours)

**Additional context**
Software is OneUI 6.1

<details open>
<summary>Device Information</summary>
<br>

**Device**
Platform: `android`
Version: `v0.3.0-prerelease+dd1dadf`
Git Hash: `dd1dadf3ad57dda036fc3532553bdb0275de6bfb`
Detail: `google_services`

**System Info**

Product: `a34xdxx`
</details>

**Comment by Airyzz** [comment]
Seems to be a common issue with OneUI, i'm seeing a lot of posts elsewhere about similar things, i suspect there's not much I can do about it as its probably an upstream issue

**Comment by ollietheotter983** [comment]
Weird thing is it works in *some* apps

**Comment by Airyzz** [comment]
Maybe some apps use an older / different version of the api? Going to close this as probably just need to wait for samsung to fix it
