### ISSUE TITLE
Matrix.org and it's alternatives for social login

### ISSUE THREAD

**Issue by ShalokShalom** [commetchat/commet#356]
Hi lovely people 😊

First of all, I like the social login.
I really think, this could help with the adoption of both Comment and Matrix.

Choosing matrix.org as the instance, is understandable, and probably not a good solution longterm.

It has proven again and again that its overwhelmed with its userbase, and the dead slow Synapse implementation is a big part of that.

I understand there might be no proper alternative for a feature like that, as of now. 

I leave this issue open, so potential alternatives can be considered and discussed in the near future.

Maybe somebody has an idea?

We are using Conduwuit since quite a while, but no real hosted instance seems to be available.

**Comment by Airyzz** [comment]
hi, I'm not sure I understand what is being requested here - some further clarification would be appreciated

**Comment by ShalokShalom** [comment]
Do you know what a social login is?

You guys are having that. But only and automatically for and with matrix.org as homeserver.

That is not fitting the federated nature of Matrix, and that instance in particular is already overloaded and crowded as heck.

Please consider alternatives.

**Comment by Airyzz** [comment]
it works with any home server, matrix.org is just the default - you want more default options?

**Comment by Airyzz** [comment]
that likely means your homeserver does not support the feature
