### ISSUE TITLE
Weird spacing in bridged chats

### ISSUE THREAD

**Issue by ollietheotter983** [commetchat/commet#358]
**Describe the bug**
Messages are seperated by icon and nametag from the sender in bridged chats (i cannot word this well so the pics should hopefully help)

**To Reproduce**
1. Go to a bridged chat (e.g. whatsapp chat) in Commet
2. Send a few messages
3. See it split them up as if there was something between

**Expected behavior**
See screenshots

**Screenshots**
Current result:
![Screenshot_20240930_211104_Commet.jpg](https://github.com/user-attachments/assets/870f1296-f669-4fcb-9b2e-4e9f8d8b03f8)

How it should group (in Element bc it works):

![Screenshot_20240930_211136_Element.jpg](https://github.com/user-attachments/assets/388ffdd1-7a48-484f-ba8a-80d23fab4f9d)

**Additional context**
I feel like it could be solved by just running like a one minute timer or so on message send, and grouping the messages together if its within the timer regardless of who sends it as long as there isnt an interruption by someone else

<details open>
<summary>Device Information</summary>
<br>

**Device**
Platform: `android`
Version: `v0.3.0-prerelease+2973942`
Git Hash: `2973942d27cd36c305687a5cbcdbd8ac35b17df9`
Detail: `google_services`

**System Info**

Product: `a34xdxx`
</details>

**Comment by Airyzz** [comment]
My suspicion is that there are unknown event types being sent in between those two messages, which dont get rendered but do interrupt the normal spacing. If you enable developer mode, it will render unknown events and you can check

**Comment by ollietheotter983** [comment]
That seems to be the issue

**Comment by ollietheotter983** [comment]
![Screenshot_20241009_085223_Commet.jpg](https://github.com/user-attachments/assets/c694dfea-0d18-40cb-84d2-2c7f2f1d56ae)

**Comment by ollietheotter983** [comment]
i guess the solution would be make the spacing ignore what isnt visible?
