### ISSUE TITLE
Frequent "unable to load account" error

### ISSUE THREAD

**Issue by ollietheotter983** [commetchat/commet#370]
This happens semi often but its happened three times today. never had this issue on another client. only fixed by logging out and logging back in. all chats disappear except ones that have had messages since the error![Screenshot_20241012_173611_Commet.jpg](https://github.com/user-attachments/assets/13b2a22d-e6bf-49a2-935a-89baa22d369c)

**Comment by Airyzz** [comment]
can you check the logs

**Comment by ollietheotter983** [comment]
> can you check the logs

will do next time i get the error :)

**Comment by ollietheotter983** [comment]
> can you check the logs

![Screenshot_20241019_173946_Commet.jpg](https://github.com/user-attachments/assets/8a9e540e-3042-4a09-9dcf-2e90af4e6301)

**Comment by Airyzz** [comment]
I think this is already fixed in #353
