### ISSUE TITLE
Graphics broken with 0.3.0

### ISSUE THREAD

**Issue by CrimsonFork** [commetchat/commet#377]
Since the update the app just shows a grey screen once past the login. It works in the background and sends notifications, but that's about it.

![Screenshot_20241026_102748_Commet](https://github.com/user-attachments/assets/15d843fa-a6d5-4449-a359-afe478e9d144)

Happens on Samsung Galaxy S20FE stock ROM Android 13.

**Comment by CrimsonFork** [comment]
Clicking on a notification makes it work as expected. But quitting and reopening returns the bug.

Of note may be that an upgrade from the last version made it drop the login.

**Comment by Airyzz** [comment]
You may just need to clear app data and log in again

**Comment by Airyzz** [comment]
closing this. if it persists we can reopen
