### ISSUE TITLE
Missing Country flag emojis

### ISSUE THREAD

**Issue by gedeondoescode** [commetchat/commet#97]
**Describe the bug**
country flag emojis don't show up on Windows

**Expected behavior**
Country flag emojis should generally show up in the picker.

**Screenshots**
![image](https://github.com/commetchat/commet/assets/75461444/fe97f0bd-9a16-49d6-9423-a85622e24400)

<details open>
<summary>Device Information</summary>
<br>

**Device**
Platform: `windows`
Version: `v0.1.0`
Git Hash: `9f69a41ff2a5a2fb9d7cd9036197c2599c6cf9ca`
Detail: `default`

**System Info**

</details>

**Comment by Airyzz** [comment]
Hey, yea this is an unfortunate side effect of #93 

The windows system emoji seems to be lacking a considerable amount of stuff. Its a temporary work around until we can figure out what color font formats flutter windows supports so we can go back to using a different emoji set.

Might close this issue and add some more info to #93 if that works for you?

**Comment by gedeondoescode** [comment]
Fine by me!  On Thu, Sep 28, 2023 at 5:15 PM, Airyzz ***@***.***> wrote:  
Hey, yea this is an unfortunate side effect of #93
The windows system emoji seems to be lacking a considerable amount of stuff. Its a temporary work around until we can figure out what color font formats flutter windows supports so we can go back to using a different emoji set.
Might close this issue and add some more info to #93 if that works for you?
