### ISSUE TITLE
Notification settings not being saved

### ISSUE THREAD

**Issue by gedeondoescode** [commetchat/commet#99]
Notification settings are not being saved per room.

**Comment by Airyzz** [comment]
Seems to be working for me, is it broken for every room or just specific ones?

**Comment by gedeondoescode** [comment]
Doesn't seem to work for any of the rooms. At least for those inside Spaces. Should mention this affects me on Windows.

**Comment by Airyzz** [comment]
Ah seems that it only works if you select 'Mute'. If you pick 'Mentions & Keywords' it does not save properly! 
Good find, thanks for the report!
